title: Benjamin Cunningham
email: bencunningham17@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Benjamin Cunningham's personal site
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  ben-cunningham

# Build settings
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
